packages:
  - back
  - front

linkWorkspacePackages: true

catalog:
  "@eslint/js": 9.39.3
  "@tailwindcss/vite": 4.2.1
  "@tanstack/react-pacer": 0.20.0
  "@tanstack/react-query": 5.90.21
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.2
  "@types/express": 5.0.6
  "@types/node": 25.3.3
  "@types/pg": 8.16.0
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 5.1.1
  "@vitest/ui": 4.1.5
  concurrently: 9.2.1
  dotenv: 17.3.1
  drizzle-kit: 0.31.9
  drizzle-orm: 0.45.1
  eslint: 9.39.3
  eslint-plugin-react-dom: 2.13.0
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.4.24
  eslint-plugin-react-x: 2.13.0
  express: 5.2.1
  express-rate-limit: 8.3.1
  globals: 16.5.0
  jsdom: 29.1.0
  lru-cache: 11.2.7
  ol: 10.8.0
  pg: 8.19.0
  prettier: 3.8.1
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: 4.2.1
  tsx: 4.21.0
  typescript: 5.9.3
  typescript-eslint: 8.56.1
  vite: 7.3.1
  vitest: 4.1.5
  zod: 4.3.6
  zustand: 5.0.11
