name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: pnpm install --frozen-lockfile
    - run: npm run checks

  build_front:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
    - uses: actions/checkout@v6
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: pnpm install --frozen-lockfile
    - run: npm run lint
    - run: npm run type-check
    - run: npm run format-check
    - run: npm run build

  build_back:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
    - uses: actions/checkout@v6
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: pnpm install --frozen-lockfile
    - run: npm run lint
    - run: npm run type-check
    - run: npm run format-check
    - run: npm run build
